### ISSUE TITLE
Improvement: Add a buildwatch commad.

### ISSUE THREAD

**Issue by mxswat** [Konijima/project-zomboid-studio#4]
I have a terrible memory and keep forgetting to build between changes during the day.
So, I'm asking if it's possible to have a `pzstudio buildwatch` command that builds first and then watches after the successful build.

**Comment by Konijima** [comment]
@mxswat there is a package json which offer some commands.

try `npm run watch` it will clean, build then watch.

**Comment by mxswat** [comment]
Yep, it works!
